syntax = "proto3";

package order;

import "google/protobuf/empty.proto";

service OrderService {
  rpc CreateOrder(CreateOrderRequest) returns (Order);

  rpc GetOrderById(EntityIdRequest) returns (Order);

  rpc UpdateOrderStatus(UpdateOrderStatusRequest) returns (Order);

  rpc DeleteOrder(EntityIdRequest) returns (google.protobuf.Empty);

  rpc ListOrders(google.protobuf.Empty) returns (OrderListResponse);
}

enum OrderStatus {
  PENDING = 0;
  COMPLETED = 1;
  CANCELLED = 2;
}

message Order {
  int32 id = 1;
  int32 userId = 2;
  OrderStatus status = 3;
  double totalAmount = 4;
  repeated OrderItem items = 5;
  string createdAt = 6;
  string updatedAt = 7;
}

message OrderItem {
  int32 productId = 1;
  int32 quantity = 2;
  double unitPrice = 3;
}

message CreateOrderRequest {
  int32 userId = 1;
  repeated CreateOrderItemRequest items = 2;
}

message CreateOrderItemRequest {
  int32 productId = 1;
  int32 quantity = 2;
}

message UpdateOrderStatusRequest {
  int32 id = 1;
  OrderStatus status = 2;
}

message EntityIdRequest {
  int32 id = 1;
}

message OrderListResponse {
  repeated Order data = 1;
}