syntax = "proto3";

package order;

import "google/protobuf/empty.proto";

service OrderService {
  rpc create(CreateOrderRequest) returns (Order);
  rpc getById(EntityIdRequest) returns (Order);
  rpc delete(EntityIdRequest) returns (google.protobuf.Empty);
  rpc list(ListOrderRequest) returns (OrderListResponse);
}

message Order {
  int32 id = 1;
  int32 userId = 2;
  int32 productId = 3;
  double totalAmount = 4;
  string createdAt = 5;
  string updatedAt = 6;
}

message CreateOrderRequest {
  int32 userId = 1;
  int32 productId = 2;
  double totalAmount = 3;
}

message EntityIdRequest {
  int32 id = 1;
}

message OrderListResponse {
  repeated Order data = 1;
  PaginationMeta meta = 2;
}

message PaginationMeta {
  int32 page = 1;
  int32 limit = 2;
  int32 total = 3;
  int32 totalPages = 4;
}

message ListOrderRequest {
  int32 page = 1;
  int32 limit = 2;
  optional int32 userId = 3;
  optional int32 productId = 4;
}