syntax = "proto3";

package product;

import "google/protobuf/empty.proto";

service ProductService {
  rpc create(CreateProductRequest) returns (Product);

  rpc getById(EntityIdRequest) returns (Product);

  rpc update(UpdateProductRequest) returns (Product);

  rpc delete(EntityIdRequest) returns (google.protobuf.Empty);

  rpc list(google.protobuf.Empty) returns (ProductListResponse);
}

message Product {
  int32 id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
  int32 categoryId = 5;
  string createdAt = 6;
  string updatedAt = 7;
}

message CreateProductRequest {
  string name = 1;
  string description = 2;
  double price = 3;
  int32 categoryId = 4;
}

message UpdateProductRequest {
  int32 id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
  int32 categoryId = 5;
}

message EntityIdRequest {
  int32 id = 1;
}

message ProductListResponse {
  repeated Product data = 1;
}