syntax = "proto3";

package user;

import "google/protobuf/empty.proto";

service UserService {
  rpc CreateUser(CreateUserRequest) returns (User);

  rpc GetUserById(EntityIdRequest) returns (User);

  rpc UpdateUser(UpdateUserRequest) returns (User);

  rpc DeleteUser(EntityIdRequest) returns (google.protobuf.Empty);

  rpc ListUsers(google.protobuf.Empty) returns (UserListResponse);
}

message User {
  int32 id = 1;
  string name = 2;
  string email = 3;
  string createdAt = 4;
  string updatedAt = 5;
}

message CreateUserRequest {
  string name = 1;
  string email = 2;
  string password = 3;
}

message UpdateUserRequest {
  int32 id = 1;
  string name = 2;
  string email = 3;
  string password = 4;
}

message EntityIdRequest {
  int32 id = 1;
}

message UserListResponse {
  repeated User data = 1;
}