syntax = "proto3";

package user;

import "google/protobuf/empty.proto";

service UserService {
  rpc create(CreateUserRequest) returns (User);

  rpc getById(EntityIdRequest) returns (User);

  rpc update(UpdateUserRequest) returns (User);

  rpc delete(EntityIdRequest) returns (google.protobuf.Empty);

  rpc list(google.protobuf.Empty) returns (UserListResponse);
}

message User {
  int32 id = 1;
  string name = 2;
  string email = 3;
  string createdAt = 4;
  string updatedAt = 5;
}

message CreateUserRequest {
  string name = 1;
  string email = 2;
  string password = 3;
}

message UpdateUserRequest {
  int32 id = 1;
  optional string name = 2;
  optional string email = 3;
  optional string password = 4;
}

message EntityIdRequest {
  int32 id = 1;
}

message UserListResponse {
  repeated User data = 1;
}